Repository jashkenas/underscore, pull requests merged in 2020-07, with the labels that each got.

#2866 Update docs w/info on how templateSettings overrides are prioritized
  index.html
Labels: documentation, fixed

#2864 Clean up superfluous "exclusive" in _.range doc after #2035
  index.html
Labels: documentation

#2869 Transpose alias and zip/unzip documentation
  index.html
  modules/index.js
  test/arrays.js
  underscore-esm.js
  underscore-esm.js.map
  underscore.js
  underscore.js.map
Labels: documentation, enhancement

#2868 Enable flattening to a specified depth (continued)
  modules/_flatten.js
  modules/flatten.js
  test/arrays.js
  test/functions.js
  test/objects.js
  underscore-esm.js
  underscore-esm.js.map
  underscore.js
  underscore.js.map
Labels: enhancement
